package connect

import (
	"github.com/aide-cloud/universal/alog"
	"gorm.io/driver/mysql"
	_ "gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/plugin/prometheus"
	"sync"
)

var (
	mysqlDB *gorm.DB
	once    sync.Once
)

// GetMysqlConnect 获取新的数据库连接
func GetMysqlConnect(dsnMap map[string]string, log ...alog.Logger) map[string]*gorm.DB {
	var myLog = alog.NewLogger()
	if len(log) > 0 {
		myLog = log[0]
	}

	connMap := make(map[string]*gorm.DB)

	for dbName, dsn := range dsnMap {
		if dbName == "" || dsn == "" {
			continue
		}

		conn, err := gorm.Open(mysql.Open(dsn), &gorm.Config{Logger: alog.GetGormLogger(myLog)})
		if err != nil {
			myLog.Warn("mysql connect error", alog.Arg{Key: dbName, Value: dsn}, alog.Arg{Key: "err", Value: err})
			continue
		}

		err = conn.Use(prometheus.New(prometheus.Config{
			DBName:          dbName, // 使用 `DBName` 作为指标 label
			RefreshInterval: 15,     // 指标刷新频率（默认为 15 秒）
			MetricsCollector: []prometheus.MetricsCollector{
				&prometheus.MySQL{
					VariableNames: mysqlMetrics,
					Prefix:        "mysql_",
				},
			}, // 用户自定义指标
		}))
		if err != nil {
			myLog.Warn("mysql use prometheus metrics error", alog.Arg{Key: dbName, Value: dsn}, alog.Arg{Key: "err", Value: err})
		}

		connMap[dbName] = conn
	}

	return connMap
}

// GetMysqlConnectSingle 获取同一个数据库连接
func GetMysqlConnectSingle(dbName, dsn string, log ...alog.Logger) *gorm.DB {
	if mysqlDB == nil {
		once.Do(func() {
			mysqlDB = GetMysqlConnect(map[string]string{
				dbName: dsn,
			}, log...)[dbName]
		})
	}
	return mysqlDB
}

var mysqlMetrics = []string{
	"Aborted_clients",
	"Aborted_connects",
	"Binlog_cache_disk_use",
	"Binlog_cache_use",
	"Binlog_stmt_cache_disk_use",
	"Binlog_stmt_cache_use",
	"Bytes_received",
	"Bytes_sent",
	"Com_admin_commands",
	"Com_assign_to_keycache",
	"Com_alter_db",
	"Com_alter_db_upgrade",
	"Com_alter_event",
	"Com_alter_function",
	"Com_alter_instance",
	"Com_alter_procedure",
	"Com_alter_server",
	"Com_alter_table",
	"Com_alter_tablespace",
	"Com_alter_user",
	"Com_analyze",
	"Com_begin",
	"Com_binlog",
	"Com_call_procedure",
	"Com_change_db",
	"Com_change_master",
	"Com_change_repl_filter",
	"Com_check",
	"Com_checksum",
	"Com_commit",
	"Com_create_db",
	"Com_create_event",
	"Com_create_function",
	"Com_create_index",
	"Com_create_procedure",
	"Com_create_server",
	"Com_create_table",
	"Com_create_trigger",
	"Com_create_udf",
	"Com_create_user",
	"Com_create_view",
	"Com_dealloc_sql",
	"Com_delete",
	"Com_delete_multi",
	"Com_do",
	"Com_drop_db",
	"Com_drop_event",
	"Com_drop_function",
	"Com_drop_index",
	"Com_drop_procedure",
	"Com_drop_server",
	"Com_drop_table",
	"Com_drop_trigger",
	"Com_drop_user",
	"Com_drop_view",
	"Com_empty_query",
	"Com_execute_sql",
	"Com_explain_other",
	"Com_flush",
	"Com_get_diagnostics",
	"Com_grant",
	"Com_ha_close",
	"Com_ha_open",
	"Com_ha_read",
	"Com_help",
	"Com_insert",
	"Com_insert_select",
	"Com_install_plugin",
	"Com_kill",
	"Com_load",
	"Com_lock_tables",
	"Com_optimize",
	"Com_preload_keys",
	"Com_prepare_sql",
	"Com_purge",
	"Com_purge_before_date",
	"Com_release_savepoint",
	"Com_rename_table",
	"Com_rename_user",
	"Com_repair",
	"Com_replace",
	"Com_replace_select",
	"Com_reset",
	"Com_resignal",
	"Com_revoke",
	"Com_revoke_all",
	"Com_rollback",
	"Com_rollback_to_savepoint",
	"Com_savepoint",
	"Com_select",
	"Com_set_option",
	"Com_signal",
	"Com_show_binlog_events",
	"Com_show_binlogs",
	"Com_show_charsets",
	"Com_show_collations",
	"Com_show_create_db",
	"Com_show_create_event",
	"Com_show_create_func",
	"Com_show_create_proc",
	"Com_show_create_table",
	"Com_show_create_trigger",
	"Com_show_databases",
	"Com_show_engine_logs",
	"Com_show_engine_mutex",
	"Com_show_engine_status",
	"Com_show_events",
	"Com_show_errors",
	"Com_show_fields",
	"Com_show_function_code",
	"Com_show_function_status",
	"Com_show_grants",
	"Com_show_keys",
	"Com_show_master_status",
	"Com_show_open_tables",
	"Com_show_plugins",
	"Com_show_privileges",
	"Com_show_procedure_code",
	"Com_show_procedure_status",
	"Com_show_processlist",
	"Com_show_profile",
	"Com_show_profiles",
	"Com_show_relaylog_events",
	"Com_show_slave_hosts",
	"Com_show_slave_status",
	"Com_show_status",
	"Com_show_storage_engines",
	"Com_show_table_status",
	"Com_show_tables",
	"Com_show_triggers",
	"Com_show_variables",
	"Com_show_warnings",
	"Com_show_create_user",
	"Com_shutdown",
	"Com_slave_start",
	"Com_slave_stop",
	"Com_group_replication_start",
	"Com_group_replication_stop",
	"Com_stmt_execute",
	"Com_stmt_close",
	"Com_stmt_fetch",
	"Com_stmt_prepare",
	"Com_stmt_reset",
	"Com_stmt_send_long_data",
	"Com_truncate",
	"Com_uninstall_plugin",
	"Com_unlock_tables",
	"Com_update",
	"Com_update_multi",
	"Com_xa_commit",
	"Com_xa_end",
	"Com_xa_prepare",
	"Com_xa_recover",
	"Com_xa_rollback",
	"Com_xa_start",
	"Com_stmt_reprepare",
	"Connection_errors_accept",
	"Connection_errors_internal",
	"Connection_errors_max_connections",
	"Connection_errors_peer_address",
	"Connection_errors_select",
	"Connection_errors_tcpwrap",
	"Connections",
	"Created_tmp_disk_tables",
	"Created_tmp_files",
	"Created_tmp_tables",
	"Delayed_errors",
	"Delayed_insert_threads",
	"Delayed_writes",
	"Flush_commands",
	"Handler_commit",
	"Handler_delete",
	"Handler_discover",
	"Handler_external_lock",
	"Handler_mrr_init",
	"Handler_prepare",
	"Handler_read_first",
	"Handler_read_key",
	"Handler_read_last",
	"Handler_read_next",
	"Handler_read_prev",
	"Handler_read_rnd",
	"Handler_read_rnd_next",
	"Handler_rollback",
	"Handler_savepoint",
	"Handler_savepoint_rollback",
	"Handler_update",
	"Handler_write",
	"Innodb_buffer_pool_pages_data",
	"Innodb_buffer_pool_bytes_data",
	"Innodb_buffer_pool_pages_dirty",
	"Innodb_buffer_pool_bytes_dirty",
	"Innodb_buffer_pool_pages_flushed",
	"Innodb_buffer_pool_pages_free",
	"Innodb_buffer_pool_pages_misc",
	"Innodb_buffer_pool_pages_total",
	"Innodb_buffer_pool_read_ahead_rnd",
	"Innodb_buffer_pool_read_ahead",
	"Innodb_buffer_pool_read_ahead_evicted",
	"Innodb_buffer_pool_read_requests",
	"Innodb_buffer_pool_reads",
	"Innodb_buffer_pool_wait_free",
	"Innodb_buffer_pool_write_requests",
	"Innodb_data_fsyncs",
	"Innodb_data_pending_fsyncs",
	"Innodb_data_pending_reads",
	"Innodb_data_pending_writes",
	"Innodb_data_read",
	"Innodb_data_reads",
	"Innodb_data_writes",
	"Innodb_data_written",
	"Innodb_dblwr_pages_written",
	"Innodb_dblwr_writes",
	"Innodb_log_waits",
	"Innodb_log_write_requests",
	"Innodb_log_writes",
	"Innodb_os_log_fsyncs",
	"Innodb_os_log_pending_fsyncs",
	"Innodb_os_log_pending_writes",
	"Innodb_os_log_written",
	"Innodb_page_size",
	"Innodb_pages_created",
	"Innodb_pages_read",
	"Innodb_pages_written",
	"Innodb_row_lock_current_waits",
	"Innodb_row_lock_time",
	"Innodb_row_lock_time_avg",
	"Innodb_row_lock_time_max",
	"Innodb_row_lock_waits",
	"Innodb_rows_deleted",
	"Innodb_rows_inserted",
	"Innodb_rows_read",
	"Innodb_rows_updated",
	"Innodb_num_open_files",
	"Innodb_truncated_status_writes",
	"Innodb_available_undo_logs",
	"Key_blocks_not_flushed",
	"Key_blocks_unused",
	"Key_blocks_used",
	"Key_read_requests",
	"Key_reads",
	"Key_write_requests",
	"Key_writes",
	"Last_query_cost",
	"Last_query_partial_plans",
	"Locked_connects",
	"Max_execution_time_exceeded",
	"Max_execution_time_set",
	"Max_execution_time_set_failed",
	"Max_used_connections",
	"Not_flushed_delayed_rows",
	"Ongoing_anonymous_transaction_count",
	"Open_files",
	"Open_streams",
	"Open_table_definitions",
	"Open_tables",
	"Opened_files",
	"Opened_table_definitions",
	"Opened_tables",
	"Performance_schema_accounts_lost",
	"Performance_schema_cond_classes_lost",
	"Performance_schema_cond_instances_lost",
	"Performance_schema_digest_lost",
	"Performance_schema_file_classes_lost",
	"Performance_schema_file_handles_lost",
	"Performance_schema_file_instances_lost",
	"Performance_schema_hosts_lost",
	"Performance_schema_index_stat_lost",
	"Performance_schema_locker_lost",
	"Performance_schema_memory_classes_lost",
	"Performance_schema_metadata_lock_lost",
	"Performance_schema_mutex_classes_lost",
	"Performance_schema_mutex_instances_lost",
	"Performance_schema_nested_statement_lost",
	"Performance_schema_prepared_statements_lost",
	"Performance_schema_program_lost",
	"Performance_schema_rwlock_classes_lost",
	"Performance_schema_rwlock_instances_lost",
	"Performance_schema_session_connect_attrs_los",
	"Performance_schema_socket_classes_los",
	"Performance_schema_socket_instances_los",
	"Performance_schema_stage_classes_los",
	"Performance_schema_statement_classes_los",
	"Performance_schema_table_handles_los",
	"Performance_schema_table_instances_los",
	"Performance_schema_table_lock_stat_los",
	"Performance_schema_thread_classes_los",
	"Performance_schema_thread_instances_los",
	"Performance_schema_users_los",
	"Prepared_stmt_coun",
	"Qcache_free_block",
	"Qcache_free_memor",
	"Qcache_hit",
	"Qcache_insert",
	"Qcache_lowmem_prune",
	"Qcache_not_cache",
	"Qcache_queries_in_cach",
	"Qcache_total_block",
	"Querie",
	"Question",
	"Rsa_public_ke",
	"Select_full_joi",
	"Select_full_range_joi",
	"Select_rang",
	"Select_range_chec",
	"Select_sca",
	"Slave_open_temp_table",
	"Slow_launch_thread",
	"Slow_querie",
	"Sort_merge_passe",
	"Sort_rang",
	"Sort_row",
	"Sort_sca",
	"Ssl_accept_renegotiate",
	"Ssl_accept",
	"Ssl_callback_cache_hit",
	"Ssl_client_connect",
	"Ssl_connect_renegotiate",
	"Ssl_ctx_verify_dept",
	"Ssl_ctx_verify_mod",
	"Ssl_default_timeou",
	"Ssl_finished_accept",
	"Ssl_finished_connect",
	"Ssl_session_cache_hit",
	"Ssl_session_cache_misse",
	"Ssl_session_cache_mod",
	"Ssl_session_cache_overflow",
	"Ssl_session_cache_siz",
	"Ssl_session_cache_timeout",
	"Ssl_sessions_reuse",
	"Ssl_used_session_cache_entrie",
	"Ssl_verify_dept",
	"Ssl_verify_mod",
	"Table_locks_immediat",
	"Table_locks_waite",
	"Table_open_cache_hit",
	"Table_open_cache_misse",
	"Table_open_cache_overflow",
	"Tc_log_max_pages_use",
	"Tc_log_page_siz",
	"Tc_log_page_wait",
	"Threads_cache",
	"Threads_connecte",
	"Threads_create",
	"Threads_runnin",
	"Uptim",
	"Uptime_since_flush_status",
}
